name = "simselections-archive"
main = "src/worker.js"
compatibility_date = "2024-07-26"

[assets]
directory = "."
binding = "ASSETS"

[[r2_buckets]]
binding = "MUSIC_BUCKET"
bucket_name = "simselections-music"

[vars]
DISCORD_CLIENT_ID = "1543720575183360111"
DISCORD_TESTERS = "informationcake,mcjizzle,christophersisk,anxst,vetramiga,ajbergren,seansvs,andrew.tobia,_tabs_,best_orange,ginger_bitters"
